name: ponderosa

dependencies:
  - python=3.10.9
  - matplotlib=3.5.1
  - networkx=2.6.3
  - numpy=1.21.5
  - pandas=1.3.5
  - scipy=1.7.3
  - seaborn=0.11.2
  - Cython=0.29.26
  - PyYAML=6.0.1
  - conda-forge::pygraphviz
  - conda-forge::scikit-learn=1.0.2
